version: "3.8"

services:
  core-billionmail:
    image: billionmail/core:4.7.2
    container_name: core-billionmail
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    environment:
      - TZ=${TZ}
      - FAIL2BAN_INIT=${FAIL2BAN_INIT:-y}
    volumes:
      - ./ssl:/etc/ssl/mail
      - ./ssl-self-signed:/etc/ssl/ssl-self-signed
      - ./core-data:/opt/billionmail/core/data
      - ./logs:/opt/billionmail/logs
    restart: always

  webmail-billionmail:
    image: roundcube/roundcubemail:1.6.10-fpm-alpine
    container_name: webmail-billionmail
    ports:
      - "${WEBMAIL_PORT:-8080}:80"
    environment:
      - TZ=${TZ}
    volumes:
      - ./webmail-data:/var/www/html
      - ./conf/webmail:/var/roundcube/config
    restart: always

